import { Room, FloorPlan, Booking, Sensor } from '@/types';

export const mockSensors: Sensor[] = [
  { id: 'motion-001', type: 'motion', status: 'active', lastReading: new Date() },
  { id: 'door-001', type: 'door', status: 'active', lastReading: new Date() },
  { id: 'temp-001', type: 'temperature', status: 'active', value: 22.5, lastReading: new Date() },
  { id: 'hum-001', type: 'humidity', status: 'active', value: 45, lastReading: new Date() },
];

const makeSensors = (suffix: string) =>
  mockSensors.map(s => ({ ...s, id: s.id.replace('001', suffix) }));

export const mockRooms: Room[] = [
  // === SCIENCE BLOCK ===
  {
    id: 'room-101',
    name: 'Lecture Hall A',
    building: 'Science Block',
    floor: 1,
    capacity: 120,
    currentOccupancy: 85,
    status: 'occupied',
    department: 'College of Science and Technology',
    coordinates: { x: 50, y: 50, width: 200, height: 120 },
    sensors: makeSensors('s01'),
    lastUpdated: new Date(),
    temperature: 22.5,
    humidity: 45,
  },
  {
    id: 'room-102',
    name: 'Seminar Room B',
    building: 'Science Block',
    floor: 1,
    capacity: 40,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Science and Technology',
    coordinates: { x: 280, y: 50, width: 150, height: 100 },
    sensors: makeSensors('s02'),
    lastUpdated: new Date(),
    temperature: 21.0,
    humidity: 42,
  },
  {
    id: 'room-103',
    name: 'Physics Lab',
    building: 'Science Block',
    floor: 1,
    capacity: 30,
    currentOccupancy: 25,
    status: 'occupied',
    department: 'College of Science and Technology',
    coordinates: { x: 50, y: 200, width: 180, height: 100 },
    sensors: makeSensors('s03'),
    lastUpdated: new Date(),
    temperature: 23.0,
    humidity: 50,
  },
  {
    id: 'room-104',
    name: 'Chemistry Lab',
    building: 'Science Block',
    floor: 2,
    capacity: 30,
    currentOccupancy: 0,
    status: 'maintenance',
    department: 'College of Science and Technology',
    coordinates: { x: 250, y: 200, width: 180, height: 100 },
    sensors: makeSensors('s04'),
    lastUpdated: new Date(),
  },
  {
    id: 'room-105',
    name: 'Study Room 1',
    building: 'Science Block',
    floor: 2,
    capacity: 12,
    currentOccupancy: 8,
    status: 'occupied',
    department: 'College of Science and Technology',
    coordinates: { x: 440, y: 50, width: 90, height: 70 },
    sensors: makeSensors('s05'),
    lastUpdated: new Date(),
    temperature: 21.5,
    humidity: 40,
  },
  {
    id: 'room-106',
    name: 'Study Room 2',
    building: 'Science Block',
    floor: 2,
    capacity: 12,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Science and Technology',
    coordinates: { x: 440, y: 130, width: 90, height: 70 },
    sensors: makeSensors('s06'),
    lastUpdated: new Date(),
    temperature: 21.0,
    humidity: 38,
  },
  {
    id: 'room-107',
    name: 'Conference Room',
    building: 'Science Block',
    floor: 1,
    capacity: 20,
    currentOccupancy: 0,
    status: 'cleaning',
    department: 'College of Science and Technology',
    coordinates: { x: 440, y: 210, width: 100, height: 90 },
    sensors: makeSensors('s07'),
    lastUpdated: new Date(),
  },

  // === ENGINEERING BLOCK ===
  {
    id: 'room-201',
    name: 'EEB Lecture Hall 1',
    building: 'Engineering Block',
    floor: 1,
    capacity: 200,
    currentOccupancy: 150,
    status: 'occupied',
    department: 'College of Engineering',
    coordinates: { x: 50, y: 50, width: 250, height: 150 },
    sensors: makeSensors('e01'),
    lastUpdated: new Date(),
    temperature: 24.0,
    humidity: 52,
  },
  {
    id: 'room-202',
    name: 'EEB Lecture Hall 2',
    building: 'Engineering Block',
    floor: 1,
    capacity: 150,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Engineering',
    coordinates: { x: 320, y: 50, width: 200, height: 130 },
    sensors: makeSensors('e02'),
    lastUpdated: new Date(),
    temperature: 22.0,
    humidity: 44,
  },
  {
    id: 'room-203',
    name: 'EEB Computer Lab 1',
    building: 'Engineering Block',
    floor: 2,
    capacity: 50,
    currentOccupancy: 35,
    status: 'occupied',
    department: 'College of Engineering',
    coordinates: { x: 50, y: 220, width: 180, height: 110 },
    sensors: makeSensors('e03'),
    lastUpdated: new Date(),
    temperature: 20.5,
    humidity: 40,
  },
  {
    id: 'room-204',
    name: 'EEB Computer Lab 2',
    building: 'Engineering Block',
    floor: 2,
    capacity: 50,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Engineering',
    coordinates: { x: 250, y: 220, width: 180, height: 110 },
    sensors: makeSensors('e04'),
    lastUpdated: new Date(),
    temperature: 21.0,
    humidity: 38,
  },
  {
    id: 'room-205',
    name: 'EEB Workshop A',
    building: 'Engineering Block',
    floor: 1,
    capacity: 40,
    currentOccupancy: 20,
    status: 'occupied',
    department: 'College of Engineering',
    coordinates: { x: 440, y: 50, width: 130, height: 100 },
    sensors: makeSensors('e05'),
    lastUpdated: new Date(),
    temperature: 25.0,
    humidity: 55,
  },
  {
    id: 'room-206',
    name: 'EEB Workshop B',
    building: 'Engineering Block',
    floor: 1,
    capacity: 40,
    currentOccupancy: 0,
    status: 'maintenance',
    department: 'College of Engineering',
    coordinates: { x: 440, y: 165, width: 130, height: 100 },
    sensors: makeSensors('e06'),
    lastUpdated: new Date(),
  },
  {
    id: 'room-207',
    name: 'EEB Seminar Room',
    building: 'Engineering Block',
    floor: 3,
    capacity: 30,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Engineering',
    coordinates: { x: 50, y: 340, width: 150, height: 90 },
    sensors: makeSensors('e07'),
    lastUpdated: new Date(),
    temperature: 22.5,
    humidity: 41,
  },
  {
    id: 'room-208',
    name: 'EEB Design Studio',
    building: 'Engineering Block',
    floor: 3,
    capacity: 25,
    currentOccupancy: 10,
    status: 'occupied',
    department: 'College of Engineering',
    coordinates: { x: 215, y: 340, width: 150, height: 90 },
    sensors: makeSensors('e08'),
    lastUpdated: new Date(),
    temperature: 23.0,
    humidity: 43,
  },

  // === ARTS BLOCK ===
  {
    id: 'room-301',
    name: 'Arts Lecture Hall',
    building: 'Arts Block',
    floor: 1,
    capacity: 100,
    currentOccupancy: 60,
    status: 'occupied',
    department: 'College of Arts and Humanities',
    coordinates: { x: 50, y: 50, width: 200, height: 120 },
    sensors: makeSensors('a01'),
    lastUpdated: new Date(),
    temperature: 22.0,
    humidity: 46,
  },
  {
    id: 'room-302',
    name: 'Language Lab',
    building: 'Arts Block',
    floor: 1,
    capacity: 30,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Arts and Humanities',
    coordinates: { x: 270, y: 50, width: 140, height: 100 },
    sensors: makeSensors('a02'),
    lastUpdated: new Date(),
    temperature: 21.5,
    humidity: 43,
  },
  {
    id: 'room-303',
    name: 'Theatre Hall',
    building: 'Arts Block',
    floor: 2,
    capacity: 200,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Arts and Humanities',
    coordinates: { x: 50, y: 190, width: 250, height: 130 },
    sensors: makeSensors('a03'),
    lastUpdated: new Date(),
    temperature: 20.0,
    humidity: 40,
  },
  {
    id: 'room-304',
    name: 'Arts Seminar Room',
    building: 'Arts Block',
    floor: 2,
    capacity: 25,
    currentOccupancy: 15,
    status: 'occupied',
    department: 'College of Arts and Humanities',
    coordinates: { x: 320, y: 190, width: 130, height: 90 },
    sensors: makeSensors('a04'),
    lastUpdated: new Date(),
    temperature: 22.5,
    humidity: 44,
  },

  // === LIBRARY ===
  {
    id: 'room-401',
    name: 'Main Reading Hall',
    building: 'Library',
    floor: 1,
    capacity: 300,
    currentOccupancy: 120,
    status: 'occupied',
    department: 'Administration',
    coordinates: { x: 50, y: 50, width: 300, height: 180 },
    sensors: makeSensors('l01'),
    lastUpdated: new Date(),
    temperature: 20.0,
    humidity: 40,
  },
  {
    id: 'room-402',
    name: 'Group Study Room 1',
    building: 'Library',
    floor: 1,
    capacity: 10,
    currentOccupancy: 8,
    status: 'occupied',
    department: 'Administration',
    coordinates: { x: 370, y: 50, width: 100, height: 80 },
    sensors: makeSensors('l02'),
    lastUpdated: new Date(),
    temperature: 21.0,
    humidity: 42,
  },
  {
    id: 'room-403',
    name: 'Group Study Room 2',
    building: 'Library',
    floor: 1,
    capacity: 10,
    currentOccupancy: 0,
    status: 'available',
    department: 'Administration',
    coordinates: { x: 370, y: 145, width: 100, height: 80 },
    sensors: makeSensors('l03'),
    lastUpdated: new Date(),
    temperature: 21.0,
    humidity: 40,
  },
  {
    id: 'room-404',
    name: 'Digital Resource Center',
    building: 'Library',
    floor: 2,
    capacity: 60,
    currentOccupancy: 30,
    status: 'occupied',
    department: 'Administration',
    coordinates: { x: 50, y: 250, width: 200, height: 110 },
    sensors: makeSensors('l04'),
    lastUpdated: new Date(),
    temperature: 20.5,
    humidity: 38,
  },

  // === ADMIN BLOCK ===
  {
    id: 'room-501',
    name: 'Board Room',
    building: 'Admin Block',
    floor: 1,
    capacity: 30,
    currentOccupancy: 0,
    status: 'available',
    department: 'Administration',
    coordinates: { x: 50, y: 50, width: 160, height: 100 },
    sensors: makeSensors('m01'),
    lastUpdated: new Date(),
    temperature: 22.0,
    humidity: 45,
  },
  {
    id: 'room-502',
    name: 'Senate Chamber',
    building: 'Admin Block',
    floor: 2,
    capacity: 80,
    currentOccupancy: 0,
    status: 'available',
    department: 'Administration',
    coordinates: { x: 50, y: 170, width: 220, height: 130 },
    sensors: makeSensors('m02'),
    lastUpdated: new Date(),
    temperature: 21.5,
    humidity: 43,
  },
  {
    id: 'room-503',
    name: 'Meeting Room A',
    building: 'Admin Block',
    floor: 1,
    capacity: 15,
    currentOccupancy: 10,
    status: 'occupied',
    department: 'Administration',
    coordinates: { x: 225, y: 50, width: 120, height: 100 },
    sensors: makeSensors('m03'),
    lastUpdated: new Date(),
    temperature: 22.0,
    humidity: 44,
  },

  // === MEDICAL SCIENCES BLOCK ===
  {
    id: 'room-601',
    name: 'Clinical Skills Lab',
    building: 'Medical Sciences Block',
    floor: 1,
    capacity: 40,
    currentOccupancy: 35,
    status: 'occupied',
    department: 'College of Medicine',
    coordinates: { x: 50, y: 50, width: 180, height: 120 },
    sensors: makeSensors('med01'),
    lastUpdated: new Date(),
    temperature: 21.0,
    humidity: 50,
  },
  {
    id: 'room-602',
    name: 'Anatomy Lab',
    building: 'Medical Sciences Block',
    floor: 1,
    capacity: 30,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Medicine',
    coordinates: { x: 250, y: 50, width: 160, height: 120 },
    sensors: makeSensors('med02'),
    lastUpdated: new Date(),
    temperature: 18.0,
    humidity: 55,
  },
  {
    id: 'room-603',
    name: 'Medical Lecture Hall',
    building: 'Medical Sciences Block',
    floor: 2,
    capacity: 150,
    currentOccupancy: 90,
    status: 'occupied',
    department: 'College of Medicine',
    coordinates: { x: 50, y: 190, width: 240, height: 140 },
    sensors: makeSensors('med03'),
    lastUpdated: new Date(),
    temperature: 23.0,
    humidity: 48,
  },

  // === BUSINESS BLOCK ===
  {
    id: 'room-701',
    name: 'Business Lecture Hall',
    building: 'Business Block',
    floor: 1,
    capacity: 180,
    currentOccupancy: 120,
    status: 'occupied',
    department: 'College of Business Administration',
    coordinates: { x: 50, y: 50, width: 230, height: 140 },
    sensors: makeSensors('b01'),
    lastUpdated: new Date(),
    temperature: 22.5,
    humidity: 46,
  },
  {
    id: 'room-702',
    name: 'MBA Center Room',
    building: 'Business Block',
    floor: 2,
    capacity: 50,
    currentOccupancy: 0,
    status: 'available',
    department: 'College of Business Administration',
    coordinates: { x: 50, y: 210, width: 170, height: 110 },
    sensors: makeSensors('b02'),
    lastUpdated: new Date(),
    temperature: 21.5,
    humidity: 42,
  },
  {
    id: 'room-703',
    name: 'Entrepreneurship Lab',
    building: 'Business Block',
    floor: 2,
    capacity: 35,
    currentOccupancy: 20,
    status: 'occupied',
    department: 'College of Business Administration',
    coordinates: { x: 240, y: 210, width: 160, height: 110 },
    sensors: makeSensors('b03'),
    lastUpdated: new Date(),
    temperature: 22.0,
    humidity: 44,
  },
];

export const floorPlans: FloorPlan[] = [
  {
    id: 'fp-sci-1',
    building: 'Science Block',
    floor: 1,
    rooms: mockRooms.filter(r => r.building === 'Science Block' && r.floor === 1),
    svgPath: '',
  },
  {
    id: 'fp-eng-1',
    building: 'Engineering Block',
    floor: 1,
    rooms: mockRooms.filter(r => r.building === 'Engineering Block' && r.floor === 1),
    svgPath: '',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book-001',
    roomId: 'room-102',
    userId: 'user-001',
    userName: 'Dr. Sarah Johnson',
    startTime: new Date(Date.now() + 3600000),
    endTime: new Date(Date.now() + 7200000),
    purpose: 'Department Meeting',
    status: 'confirmed',
  },
  {
    id: 'book-002',
    roomId: 'room-106',
    userId: 'user-002',
    userName: 'Prof. Michael Chen',
    startTime: new Date(Date.now() + 1800000),
    endTime: new Date(Date.now() + 5400000),
    purpose: 'Student Consultation',
    status: 'confirmed',
  },
  {
    id: 'book-003',
    roomId: 'room-202',
    userId: 'user-003',
    userName: 'Dr. Aisha Bello',
    startTime: new Date(Date.now() + 7200000),
    endTime: new Date(Date.now() + 10800000),
    purpose: 'EEB Workshop Training',
    status: 'confirmed',
  },
  {
    id: 'book-004',
    roomId: 'room-403',
    userId: 'user-001',
    userName: 'Dr. Sarah Johnson',
    startTime: new Date(Date.now() - 86400000),
    endTime: new Date(Date.now() - 82800000),
    purpose: 'Research Group Study',
    status: 'confirmed',
  },
];

export function getRoomById(id: string): Room | undefined {
  return mockRooms.find(room => room.id === id);
}

export function getRoomsByStatus(status: Room['status']): Room[] {
  return mockRooms.filter(room => room.status === status);
}

export function getTotalOccupancy(): number {
  return mockRooms.reduce((sum, room) => sum + room.currentOccupancy, 0);
}

export function getTotalCapacity(): number {
  return mockRooms.reduce((sum, room) => sum + room.capacity, 0);
}

export function getUtilizationRate(): number {
  return Math.round((getTotalOccupancy() / getTotalCapacity()) * 100);
}

// All buildings available
export const ALL_BUILDINGS = [
  'Science Block',
  'Engineering Block',
  'Arts Block',
  'Library',
  'Admin Block',
  'Medical Sciences Block',
  'Business Block',
];

// Lead City University Departments
export const LEAD_CITY_DEPARTMENTS = [
  'College of Medicine',
  'College of Law',
  'College of Engineering',
  'College of Business Administration',
  'College of Arts and Humanities',
  'College of Science and Technology',
  'College of Social Sciences',
  'College of Education',
  'College of Nursing',
  'College of Pharmacy',
  'College of Communication and Media Studies',
  'College of Environmental Sciences',
  'College of Information Technology',
  'College of Agriculture',
  'Administration',
] as const;
